# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba763b3c20f90ed5480f08e1b7ec042c89255bc476481efa1b191862d782ffa06d9dc8648d2a360222d2c8b0c68614635db52d9877c588d46b40ba49841c6846

test:
  secret_key_base: 9d0b76605f9ce6d4ffba13a625c5cdaec8004c19abb234f333155a424ba96e93e15943c928f228578ddaa82c6c256d1ad24a3552f5c2a66c6e8669f8a7e943a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
